### ISSUE TITLE
Using rss-cli as a validator?

### ISSUE THREAD

**Issue by colindean** [Clortox/rss-cli#1]
Does `rss-cli` have a validation step or mode? 

I'm looking for a good, maintained RSS and ATOM validator -- [feed-validator](https://www.npmjs.com/package/feed-validator) and [w3c-validator-cli](https://pypi.org/project/w3c-validator-cli/) do what I want but they're unmaintained and have installation problems.

**Comment by Clortox** [comment]
It does not, sorry. This is more of a hobby project for me. You are welcome to take this code and add the functionality if you wish and I'll merge it, however I do not actively work on this project anymore.

**Comment by colindean** [comment]
Thanks for the response!
